### ISSUE TITLE
SDC Page should have a lot more content

### ISSUE THREAD

**Issue by ynigoreyes** [TTUSDC/TTUACM-MockUps#11]
- An expandable description ("see more" kind of deal)
- A picture or graphic

**Comment by jalelgaming** [comment]
Lol i just saw this. I already implemented it! #Thank me later ^^ :)

**Comment by jalelgaming** [comment]
I thought about everything Miggy 😝

**Comment by madewithsmiles** [comment]
Sorry Miggy, I had commented this with my "game dev" github..I had thought about it so I had designed something for it already. Everything's in the inprogress branch. Let me know if you like the way I did it.
